### ISSUE TITLE
Hope incorporate DALI

### ISSUE THREAD

**Issue by zsz00** [tylerjthomas9/RAPIDS.jl#13]
It would be perfect if you incorporate DALI !!

https://github.com/NVIDIA/DALI

The NVIDIA Data Loading Library (DALI) is a library for data loading and pre-processing to accelerate deep learning applications. It provides a collection of highly optimized building blocks for loading and processing image, video and audio data. It can be used as a portable drop-in replacement for built in data loaders and data iterators in popular deep learning frameworks.

**Comment by tylerjthomas9** [comment]
Thank you for the suggestion! I will look into this. At a glance, this may be better in a separate library for deep learning acceleration, but I am not too familiar with DALI. The install is via pip, so I am not sure how it'll interact with the RAPIDS conda dependencies.

**Comment by zsz00** [comment]
yes, perhaps Dali would be better in a separate library
